version: '3.9'

services:
  db:
    image: postgres:latest  # Use the required PostgreSQL version
    #container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=taosif
      - POSTGRES_PASSWORD=taosif1234
      - POSTGRES_DB=Movies
    ports:
      - "5432:5432"